### ISSUE TITLE
(5 hours) Prestige button visual overflow issue

### ISSUE THREAD

**Issue by jasperfirecai2** [dan-simon/misc#12]
Probably didnt notice this earlier because it only happens lategame. 
The efficiency prestige button gain text overflows out of the button if the prestige time exceeds 10000:xx:xx and the multiplier exceeds 1e100000x.
![image](https://user-images.githubusercontent.com/8398131/88458379-ecfdfb80-ce8d-11ea-896b-4ceee143e42a.png)
Would it be possible to make the height of the container button grow with the content? Or is there some css at play that'll prevent that?

**Comment by dan-simon** [comment]
Thanks for reporting these issues! This one is hopefully fixed by http://github.com/dan-simon/misc/commit/318cb13cd84f71187a302c03e4e0bd1a8919864f. Sorry for taking a few days to make such a simple fix.

I thought that this was better than dynamically changing the button size because dynamically changing the button size might lead to weird screen jitters every prestige.

**Comment by dan-simon** [comment]
Forgot to close, sorry.

**Comment by jasperfirecai2** [comment]
No worries, i enjoyed the game from start to finish (thee is no true end, but i feel like all achievements is a good point to stop), and I want new players to get the most polished experience possible.
